# Generated by Django 4.0.5 on 2022-09-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_cname_cost_centre_c_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Alias', models.CharField(max_length=30)),
                ('Under', models.CharField(max_length=40)),
                ('Group_Subledger', models.CharField(max_length=10)),
                ('Nett_DebitCredit_Reporting', models.CharField(max_length=10)),
                ('Used_Calculation', models.CharField(max_length=10)),
                ('Method_Purchase_Invoice', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Group_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Alias', models.CharField(max_length=30)),
                ('Under', models.CharField(max_length=40)),
                ('Group_Subledger', models.CharField(max_length=10)),
                ('Nett_DebitCredit_Reporting', models.CharField(max_length=10)),
                ('Used_Calculation', models.CharField(max_length=10)),
                ('Method_Purchase_Invoice', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='First_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40)),
                ('Debit', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('Group_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.create_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='First_Voucher_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40)),
                ('Debit', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('Voucher_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.create_group_voucher_model')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Particular', models.CharField(max_length=40)),
                ('Vch_Type', models.CharField(max_length=40)),
                ('Vch_No', models.IntegerField(default=0)),
                ('DEBIT', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('Open_Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Vch_Type', models.CharField(max_length=40)),
                ('Vch_No', models.IntegerField(default=0)),
                ('Debit', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('Open_Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Stock_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40)),
                ('Quantity', models.CharField(max_length=40)),
                ('Rate', models.IntegerField(default=0)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('Fgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.first_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Item_Monthly_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Balance_Qty', models.IntegerField(default=0)),
                ('Open_Balance_Value', models.IntegerField(default=0)),
                ('Particular', models.CharField(max_length=50)),
                ('Inwards_Qty', models.IntegerField(default=0)),
                ('Inwards_Vlu', models.IntegerField(default=0)),
                ('Outwards_Qty', models.IntegerField(default=0)),
                ('Outwards_Vlu', models.IntegerField(default=0)),
                ('Closing_Bal_Qty', models.IntegerField(default=0)),
                ('Closing_Bal_Vlu', models.IntegerField(default=0)),
                ('Pro_Stock_Voucher_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product_stock_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=50)),
                ('Sgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.second_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Item_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Particular', models.CharField(max_length=50)),
                ('Voucher_Type', models.CharField(default='pay', max_length=40)),
                ('Vch_No', models.IntegerField(default=0)),
                ('Inwards_Qty', models.IntegerField(default=0)),
                ('Inwards_Vlu', models.IntegerField(default=0)),
                ('Outwards_Qty', models.IntegerField(default=0)),
                ('Outwards_Vlu', models.IntegerField(default=0)),
                ('Pro_Stock_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item_monthly_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40)),
                ('Quantity', models.IntegerField(default=0)),
                ('Rate', models.IntegerField(default=0)),
                ('Value', models.IntegerField(default=0)),
                ('Stock_Voucher_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.create_group_voucher_model')),
            ],
        ),
        migrations.CreateModel(
            name='Second_Voucher_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40)),
                ('Debit', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('FVoucher_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.first_voucher_summary_model')),
            ],
        ),
        migrations.AddField(
            model_name='product_stock_group_summary_model',
            name='PStock_Voucher_Forgn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_group_summary_model'),
        ),
        migrations.CreateModel(
            name='Ledger_Monthly_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Balance', models.IntegerField(default=0)),
                ('Particular', models.CharField(max_length=30)),
                ('Dedit', models.IntegerField(default=0)),
                ('Credit', models.IntegerField(default=0)),
                ('Closing_Balance', models.IntegerField(default=0)),
                ('Tgroup_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.third_group_summary_model')),
            ],
        ),
    ]
